
include ../../inc/make.inc

TOP=ppu_hdmi_top
DEVICE=xc7z010clg400-1
DEVICE_SHORT=xc7z010_1
HDL_SOURCE = $(CLK_SOURCE) $(HDMI_SOURCE) $(PPU_SOURCE) $(TOP).sv
CONSTRIANTS = $(CLOCK_XDC) $(HDMI_XDC) $(ARTYZ7_XDC)

include ../../inc/make.hw

